### ISSUE TITLE
Sidebar redesign mockups

### ISSUE THREAD

**Issue by BradenLawrence** [ember-learn/ember-styleguide#191]
Adding some mockups for the sidebar redesign. These use the navbar from the [Website Redesign RFC](https://github.com/emberjs/rfcs/blob/master/text/0425-website-redesign.md), and the current Releases page as sample page content.

Objectives for this redesign:
- Create a sidebar that can unify the 4 currently in use on emberjs.com
- Should allow for 2, and up to 3 levels of links
- Items should be allowed to display as expanded or collapsed
- Should allow items to be displayed expanded by default

1. ![Ember-sidebar-06](https://user-images.githubusercontent.com/17574170/60699695-16369d00-9ec3-11e9-8be1-b1f40f0d9946.png)
2. ![Ember-sidebar-04](https://user-images.githubusercontent.com/17574170/60699723-35cdc580-9ec3-11e9-9163-633b5ba6560d.png)
3. ![Ember-sidebar-01](https://user-images.githubusercontent.com/17574170/60699740-467e3b80-9ec3-11e9-98db-0b531589d00e.png)
4. ![Ember-sidebar-03](https://user-images.githubusercontent.com/17574170/60699770-59910b80-9ec3-11e9-8d1d-327ee19a6abb.png)

I'd like to get some feedback to see if there is anything I overlooked, whether these fit within the current branding guidelines, and any other areas we can improve.

**Comment by ghislaineguerin** [comment]
Hi @BradenLawrence, thanks for working on these. I have drafted a list of requirements that the new sidebar design needs to consider on issue #209 
Feel free to refer to [the styleguide](https://deploy-preview-145--ember-styleguide.netlify.com/) in order to apply typography, colors and spacing to your design.
If anything is missing from the styleguide that prevents the implementatio of all requirements, we need an issue for that as well.
Let me know if you have any questions.

**Comment by mansona** [comment]
Hey @BradenLawrence I hope you don't mind that I close this in favour of https://github.com/ember-learn/ember-styleguide/issues/209 ? It seems like there is a lot of discussion happening over there and I want to rally behind that effort when getting contributors involved 👍 

Let me know if you think I should reopen this, or if you think that there is any info missing from #209
