### ISSUE TITLE
padding around edges in mobile view

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-styleguide#231]
Currently the `.container` class is the main class that we use to enforce the fixed width of the website. On desktop this looks great with the `margin: auto` centring the content effectively :tada:

on mobile (or at any time that the margin has collapsed to nothing) the content is jammed right up against the edges of the UI 

[Example of text right up against the edge of the screen](https://user-images.githubusercontent.com/594890/67718276-587e6f80-f9c7-11e9-8077-466ddc6ec5be.png)

I think we could add some padding to the `.container` class to solve this issue effectively but I assume @pichfl or @ghislaineguerin might have some more to say on the issue 😂

**Comment by pichfl** [comment]
The `.container` should not have a fixed size on mobile, only padding. The padding on each side on narrow screens equals half the width of the column gap and comes at 12dp which is, in our case, `1.5rem`.

![image](https://user-images.githubusercontent.com/194641/67765900-86a69280-fa4d-11e9-8b64-de0ce2c8899f.png)

On larger screens, the column gap is 32dp or `4rem`, I'd use the same calculation and add `2rem` to each side. 

I do recommend setting those values directly and not using `calc()` as `calc()` has outrageous bugs in IE11.

Remember to use `box-sizing: content-box;` for the large screen, otherwise the padding will be part of the total width.

**Comment by pichfl** [comment]
This should not in any way touch the grid aspects of the implementation, the grid I'm talking about is only relevant in terms of the design.

**Comment by mansona** [comment]
closed in #238
