### ISSUE TITLE
New designs needed for search autocomplete

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-styleguide#299]
## Current implementation

<details>
<summary>
https://api.emberjs.com
</summary>

<img width="1440" alt="Screenshot 2020-03-30 18 18 05" src="https://user-images.githubusercontent.com/604117/77967373-fba71e00-72b2-11ea-9df9-67a5b310f956.png">
</details>

<details>
<summary>
https://guides.emberjs.com
</summary>

<img width="1440" alt="Screenshot 2020-03-30 18 18 30" src="https://user-images.githubusercontent.com/604117/77967381-fe097800-72b2-11ea-8989-411f74a12ab3.png">

</details>

The new design should include the "Search by Algolia" attribution seen in guides search result.

**Comment by mansona** [comment]
I am closing this issue in favour of repo-specific issues: 

- https://github.com/ember-learn/guidemaker-ember-template/issues/41
- https://github.com/ember-learn/deprecation-app/issues/558
https://github.com/ember-learn/ember-api-docs/issues/691

This is mainly because we can't have a single shared solution for search results 😞 unfortunately
