### ISSUE TITLE
Ember Styleguide is mis-labeled in the documentation app

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#314]
## Expected Behavior
The Ember Styleguide should have the title of Ember Styleguide

## Actual Behavior
The Ember Styleguide currently says "Ember Field Guide" 

## Steps to Reproduce
Visit https://ember-styleguide.netlify.app/ and look in the top left of the page. (first items in the DOM)

**Comment by alexeykostevich** [comment]
Here is where the issue comes from:
https://github.com/empress/field-guide-default-template/blob/6de4cdf18fb67d808be21dd98fbc5481cc78041d/addon/templates/application.hbs#L10

@mansona , what do you think about the following solution?

1. Set `name` of the [Field Guide configuration](https://github.com/empress/field-guide#configuring) to `Ember Styleguide` in this repository. It can be done [here](https://github.com/ember-learn/ember-styleguide/blob/master/tests/dummy/config/environment.js#L30).
2. Update `empress/field-guide-default-template` to render `name` without a hard-coded postfix. We can also add secondary text like *"Powered by Empress Field Guide"* to keep the reference to the backing Empress project. It can be done [here](https://github.com/empress/field-guide-default-template/blob/6de4cdf18fb67d808be21dd98fbc5481cc78041d/addon/templates/application.hbs#L10).

**Comment by MelSumner** [comment]
@alexeykostevich it already indicates that it's powered by the Field Guide in the footer, so I don't think we'd need extra work there. 👍
