### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-styleguide#32]
This addon is now consumed via its git url in our other apps. git based dependency resolution is usually slow compared to packages from registries. Also `ember install` command has a weird bug where it removes git based dependencies post running it. 

Besides these factors if this is published to npm & if we enable greenkeeper on our upstream repos, then it makes it trivial to propagate changes across apps. We'll have to setup ember-cli-release so that travis can run it on merges to master to publish to npm.

Thoughts?

**Comment by MelSumner** [comment]
We just started this work; in the last(?) learning team meeting we discussed that the addon shouldn't be used yet, and that if apps needed to use certain components they'd create them in the apps for now. Everyone seemed to be okay with that course of action- did something change?

If there was something we forgot to include in the conversation, I'm happy to re-discuss- maybe put it on the learning team agenda for this week?

**Comment by sivakumar-kailasam** [comment]
Oh I just started the conversation thinking long term. If it's too early, we can just mark it for future and revisit. 

Also it was midnight here when the meeting happened, so I didn't remember this when I wrote down the issue :sweat_smile:

**Comment by mansona** [comment]
Howdy folks 👋 

Sorry, this all got lost in a bit of the back and forth. Entirely my fault, I'm trying to do better.

We discussed this not last week but the week before @MelSumner and yes you're 100% right that we agreed not to use the styleguide at that point. I then posted a **Slack Post** in the ember-learning team slack discussing a proposal to have an exception to that assertion. I think this was also before we had decided to use the discuss forum for these discussions.

I assumed that because there was no objection that it wasn't a problem, but I know now that it's more likely you never saw the post 😞 and of course my assumption was entirely wrong.

I have reposted the "post" on the discuss forum here: https://discuss.emberjs.com/t/deprecation-app-update/14270 so please weigh in and let me know your thoughts.

**Comment by MelSumner** [comment]
@mansona @serenaf @locks @sivakumar-kailasam since everyone seems to need the header and footer sooner rather than later, once we get the first round of footer finished, we can publish to npm.

**Comment by MelSumner** [comment]
Update: we (the learning team) decided to hold on this and let the addon get closer to complete.

**Comment by sivakumar-kailasam** [comment]
We've started publishing to npm :)
