### ISSUE TITLE
Add Slack

### ISSUE THREAD

**Issue by MelSumner** [ember-learn/ember-styleguide#46]
add the slack logo & link to the slackin url

**Comment by Dan-Ste** [comment]
Any thought about the usage of raw svg icons in the footer template? Maybe it is better to use some component for this purpose?

**Comment by MelSumner** [comment]
@Dan-Ste we need to double- check the components, but none of them should have any specific data in them- I think the navbar does it correctly right now, but I'm not sure if the footer does.

**Comment by Dan-Ste** [comment]
@MelSumner you mean try to make all components abstract? 
I also can see that only navbar now use a pod structure in the addon - should we stick with classic files structure or switch to pods?
And another question :) It looks like the api-docs now has different design of header and footer than ember-styleguide. Is it intentional? I personally like a design from api-docs.

**Comment by sivakumar-kailasam** [comment]
> should we stick with classic files structure or switch to pods?
Pod structure in addons have edge cases that cause problems (I love pods btw 🙂), so better we continue with classic until module unification lands. 

> It looks like the api-docs now has different design of header and footer than ember-styleguide. Is it intentional?

API docs predates the style guide so we haven't got to moving it to use style guide yet. But we'd love help with that 🙂

The header and footer reorganization has been a result of detailed discussions that have happened in the last year over GitHub & learning team meetings(notes are available on GitHub). So what we have in the website & style guide now would most likely be the default for now.
