### ISSUE TITLE
Fix sidebar-weirdness

### ISSUE THREAD

**Issue by MinThaMie** [ember-learn/ember-styleguide#486]
- [ ] negative margin magic in the guidemaker-template
- [ ] mobile styling needed in API docs
- [ ] word-wrapping for API menu items that don't include slashes

All of the fixes for these cases should go in the sidebar or table of contents CSS here in the styleguide (if we can)

**Comment by Shub3am** [comment]
Hey I was willing to work on this issue, can you reiterate where the guidemaker-template is?

**Comment by MinThaMie** [comment]
So the guidemaker-template lives here: https://github.com/ember-learn/guidemaker-ember-template

**Comment by lukasnys** [comment]
I'll pick this up!

**Comment by lukasnys** [comment]
I know it's 3 months later but I'm picking this back up 💀 

> word-wrapping for API menu items that don't include slashes

This point should likelly become "word-wrapping for API menu items that don't include dashes" as the word wrapping happens on dashes but not slashes.

**Comment by lukasnys** [comment]
@MinThaMie @mansona do either of you have an idea on the best way to about the word wrapping? Maybe a naïve approach, but could we just increase the sidebar width and decrease its padding to create more space?

e.g. the following screenshot uses a padding of `var(--spacing-2);`/`1.125rem` (instead of the current `var(--spacing-4);`/`2.25rem`) and a sidebar width of `21rem` instead of the current `18.5rem`.

If you are okay with this approach, I propose to change this directly in the ember-styleguide. Let me know what you think

<img width="2056" alt="image" src="https://github.com/ember-learn/ember-styleguide/assets/22593230/c922076e-0120-422c-b08f-9fd888a81de6">

**Comment by MinThaMie** [comment]
Should be fixed by #507

**Comment by mansona** [comment]
We will need to update to ember-styleguide@10 to get the new stuff 👍

**Comment by lukasnys** [comment]
I upgraded to ember-styleguide@9 and cleaned up the redundant styles in https://github.com/ember-learn/guidemaker-ember-template/pull/172. Ignace has already approved this but it could use another pair of eyes.

I upgraded to ember-styleguide@10 and removed the negative margin hack in https://github.com/ember-learn/guidemaker-ember-template/pull/171 if either of you could have a look :pray: (which I based on PR 172, but I can't figure out how to base my PR onto that one so it shows changes for both PRs)

**Comment by mansona** [comment]
do we still need this issue now that #171 is merged?

**Comment by mansona** [comment]
turns out not! we can close this 🎉
