### ISSUE TITLE
Code example colors are hard on the eyes in the ember guides.

### ISSUE THREAD

**Issue by alexmiddeleer** [ember-learn/ember-styleguide#75]
Just wanted to note that I think the color palette on the site might be a little bit off, or need some slight tweaking. For example at https://guides.emberjs.com/release/testing/testing-components/. I see the body has `background-color: #FDFDFD;`, the code example has `background-color: #151515;`, and the base font color of the code example has  `color: #f8f8f2`. I find this white frame, black box, white text arrangement is a hard on the eyes, but if it’s for accessibility I can certainly live with it or install an extension to tweak it to my liking. Thanks very much to everyone who worked on the site, btw, it looks great :thumbsup:

Example screenshot attached:

![image](https://user-images.githubusercontent.com/5400639/41778806-da5b8d52-75fd-11e8-9966-38d6c865541a.png)

**Comment by localpcguy** [comment]
The code example colors were changed to be more accessible a little bit back - the default colors from the plugin did not match the WCAG AA recommendations for color contrast. It's a bit tricky since the code itself has a number of different colors for the various file types, plus it has to account for diff highlighting (i.e. showing removed and inserted lines highlighted red/green). 

If changes are made, I'd ask that we try to ensure that code color contrasts still follow the accessibility guidelines (at least 1:4.5 contrast ratio).

see:
https://github.com/ember-learn/guides-app/issues/97

**Comment by MelSumner** [comment]
For now we are going to leave them the same, but we will revisit this issue as we work on the re-design. Thank you for understanding!
